#!/usr/bin/env zsh -f
fw='/usr/libexec/ApplicationFirewall/socketfilterfw'

mosh_server_sym="$(which mosh-server)"
mosh_server_abs="$(readlink -f $mosh_server_sym)"

mosh_sym="$(which mosh)"
mosh_abs="$(readlink -f $mosh_sym)"

sudo "$fw" --setglobalstate off

sudo "$fw" --add "$mosh_server_sym"
sudo "$fw" --unblockapp "$mosh_server_sym"
sudo "$fw" --add "$mosh_server_abs"
sudo "$fw" --unblockapp "$mosh_server_abs"

sudo "$fw" --add "$mosh_sym"
sudo "$fw" --unblockapp "$mosh_sym"
sudo "$fw" --add "$mosh_abs"
sudo "$fw" --unblockapp "$mosh_abs"

sudo "$fw" --setglobalstate on
