#!/usr/bin/env zsh -f
# try to mount first partition of root device as EFI
EFI_MOUNTPOINT=/Volumes/EFI

EFI_PART=$(mount | grep " / " | cut -d" " -f 1 | sed 's/[0-9][0-9]*$/1/g')
EFI_MOUNTED=$(mount | grep -c " $EFI_MOUNTPOINT ")

if [[ $EFI_MOUNTED -gt 0 ]]; then
  echo "something is already mounted to $EFI_MOUNTPOINT"
  return 1
fi
echo "trying to mount $EFI_PART to $EFI_MOUNTPOINT"
mkdir -p /Volumes/EFI && sudo mount_msdos $EFI_PART $EFI_MOUNTPOINT && echo "success"
