#!/usr/bin/env zsh -f
if [[ -z $1 ]]; then
  echo "usage: $0 <package>"
  return 1
fi
sudo pkgutil --files $1
sudo pkgutil --files $1 | sort -r | sudo xargs rm -vdf
echo "proceed with deleting package metadata?"
read answer
if [ "$answer" = y ]; then
  sudo pkgutil --forget $1
  return 0
fi
