#!/usr/bin/env zsh

cd $HOME

zsh .consart/link
source .zshrc

echo "Installing zplug..."
install_zplug

echo "Installing vimplug..."
install_vimplug

echo "Installing vim plugins..."
vim -c PlugInstall! -c qa!
