#!/usr/bin/env zsh
dotfiles=(
  tmux.conf
  vimrc
  zsh
  zshenv
  zshrc
)

echo "Linking dotfiles, will prompt to rm if exist"
foreach f in $dotfiles; do
  test -e ${HOME}/.${f} && rm -ir ${HOME}/.${f} &&
  ln -sf ${HOME}/.consart/${f} ${HOME}/.${f}
done;
