#!/usr/bin/env zsh
dotfiles=(
  tmux.conf
  vimrc
  zsh
  zshenv
  zshrc
)

if [[ "$1" == "-h" ]]; then
  echo "link dotfiles from consart\n\n" 
  echo "usage: $0 [-f # force overwrite ]"
fi

if [[ "$1" == "-f" ]]; then
  FORCE_FLAG=1
else
  FORCE_FLAG=0
fi

if [[ ! -f ${HOME}/.consart/link ]]; then
  echo "please install (or link) consart to ~/.consart" 
  return 1
fi

echo "Linking dotfiles"

foreach f in $dotfiles; do
  link_src=${HOME}/.consart/${f}
  link_dest=${HOME}/.${f}
  echo "$link_dest \t -> $link_src"
  if [ $FORCE_FLAG -ne 1 ]; then
    test -e $link_dest && rm -ir $link_dest
    ln -s $link_src $link_dest
  else
    ln -sf $link_src $link_dest
  fi
done;

# gitconfig
link_src=${HOME}/.consart/misc/gitconfig
link_dest=${HOME}/.gitconfig
echo "$link_dest \t -> $link_src"
if [ $FORCE_FLAG -ne 1 ]; then
  test -e $link_dest && rm -ir $link_dest
  ln -s $link_src $link_dest
else
  ln -sf $link_src $link_dest
fi

# antidote plugins list
link_src=${HOME}/.consart/zsh/zsh_plugins.txt
link_dest=${HOME}/.zsh_plugins.txt
echo "$link_dest \t -> $link_src"
if [ $FORCE_FLAG -ne 1 ]; then
  test -e $link_dest && rm -ir $link_dest
  ln -s $link_src $link_dest
else
  ln -sf $link_src $link_dest
fi

# neovim to use vimrc
mkdir -p ${HOME}/.config/nvim
link_src=${HOME}/.consart/misc/config-nvim-init.vim
link_dest=${HOME}/.config/nvim/init.vim
echo "$link_dest \t -> $link_src"
if [ $FORCE_FLAG -ne 1 ]; then
  test -e $link_dest && rm -ir $link_dest
  ln -s $link_src $link_dest
else
  ln -sf $link_src $link_dest
fi

# ghostty
if command -v ghostty &>/dev/null; then
  mkdir -p ${HOME}/.config/ghostty
  link_src=${HOME}/.consart/X/config.ghostty
  link_dest=${HOME}/.config/ghostty/config.ghostty
  echo "$link_dest \t -> $link_src"
  if [ $FORCE_FLAG -ne 1 ]; then
    test -e $link_dest && rm -ir $link_dest
    ln -s $link_src $link_dest
  else
    ln -sf $link_src $link_dest
  fi
fi

# waybar
if command -v waybar &>/dev/null; then
  mkdir -p ${HOME}/.config/waybar
  for f in config.jsonc style.css; do
    link_src=${HOME}/.consart/X/waybar/${f}
    link_dest=${HOME}/.config/waybar/${f}
    echo "$link_dest \t -> $link_src"
    if [ $FORCE_FLAG -ne 1 ]; then
      test -e $link_dest && rm -ir $link_dest
      ln -s $link_src $link_dest
    else
      ln -sf $link_src $link_dest
    fi
  done
fi

# sway
if command -v sway &>/dev/null; then
  mkdir -p ${HOME}/.config/sway
  link_src=${HOME}/.consart/X/sway/config
  link_dest=${HOME}/.config/sway/config
  echo "$link_dest \t -> $link_src"
  if [ $FORCE_FLAG -ne 1 ]; then
    test -e $link_dest && rm -ir $link_dest
    ln -s $link_src $link_dest
  else
    ln -sf $link_src $link_dest
  fi
fi
