#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config top_padding          25

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor DP1 -d I-1 I-2 I-3 I-4 I-5
#bspc monitor DP2 -d II-6 II-7 II-8 II-9 II-0
#bspc monitor -s DP2

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Plasma floating=on
bspc rule -a Plasma-desktop floating=on
