#!/usr/bin/env -S zsh -f

if iscmd distrobox; then
  if [[ -z $1 ]]; then
    if iscmd fzf; then
      local box=$(distrobox list --no-color | tail -n +2 | awk -F'|' '{gsub(/^ +| +$/, "", $2); print $2}' | fzf)
      [[ -z $box ]] && return 1
      distrobox enter $box
    else
      echo "usage: $0 [name]"
      echo "\tinstall fzf for list menu"
    fi
  else
    distrobox enter $1
  fi
elif iscmd docker; then
  docker exec -ti "$@"
else
  echo "neither distrobox nor docker found"
  return 1
fi
