#!/usr/bin/env zsh
if [[ -z $1 ]]; then
  echo "usage: $0 <repo address> <local dir>"
  return 1
fi
if ! iscmd git; then
  echo "git is not installed"
  return 1
fi

local repo=$1
local workdir

if [[ -z $2 ]]; then
  workdir=$1:t:r # tail w/o ext
else
  workdir=$2
fi

if [[ -d $workdir/.git ]]; then
  echo "$workdir already exists, trying to update instead"
  git-up $workdir
else
  # Sourced from antigen url resolution logic.
  # https://github.com/zsh-users/antigen/blob/master/antigen.zsh
  # Expand short github url syntax: `username/reponame`.
  if [[ $repo != git://* &&
        $repo != https://* &&
        $repo != http://* &&
        $repo != ssh://* &&
        $repo != git@github.com:*/*
        ]]; then
      repo="https://github.com/${repo%.git}.git"
  fi
  git clone $repo $workdir
fi
