#!/usr/bin/env zsh -f
if [[ -z $2 ]]; then
  echo "usage: $0 <repo address> <install dir>"
  return 1
fi
if ! iscmd git; then
  echo "git is not installed"
  return 1
fi

GIT_REPO=$1
INSTALL_DIR=$2

if [[ -d $INSTALL_DIR ]]; then
  echo "$INSTALL_DIR already exists, do you want to update instead?"
  read answer
  if [[ $answer =~ ^ye?s?$ ]]; then
    git-up $INSTALL_DIR
  fi
else
  mkdir -p $INSTALL_DIR
  git clone $GIT_REPO $INSTALL_DIR
fi


