#!/usr/bin/env zsh -f
# prepares the shell for oracle stuff

if [[ -z $ORACLE_HOME_DB || -z $ORACLE_HOME_GRID ]]; then
  echo "you must set ORACLE_HOME_DB or ORACLE_HOME_GRID in your zshrc.local"
  return 1
fi

if [[ -z $1 ]]; then
  echo "usage: $0 <db|grid>"
  return 1
fi

if [[ $1 == 'db' && -d $ORACLE_HOME_DB ]]; then
  export ORACLE_HOME=$ORACLE_HOME_DB
  export PATH=${ORACLE_HOME}/bin:${PATH}
  echo "OK"
fi

if [[ $1 == 'grid' && -d $ORACLE_HOME_GRID ]]; then
  export ORACLE_HOME=$ORACLE_HOME_GRID
  export PATH=${ORACLE_HOME}/bin:${PATH}
  echo "OK"
fi

if iscmd rlwrap; then
  alias sqlplus="rlwrap sqlplus"
  alias sql="rlwrap sqlplus / as sysdba"
  alias rman="rlwrap rman"
  alias asmcmd="rlwrap asmcmd"
fi
return 0
