#!/usr/bin/env zsh -f
case $OSTYPE in
darwin*)
if [[ `uname` != "Darwin" ]]; then
  echo "this function is for OSX only"
  return 1
fi
if [[ -z $1 ]]; then
  echo "usage: $0 <package>"
  return 1
fi
sudo pkgutil --files $1
sudo pkgutil --files $1 | sort -r | sudo xargs rm -vdf
echo "proceed with deleting package metadata?"
read answer
if [ "$answer" = y ]; then
  sudo pkgutil --forget $1
  return 0
fi
;;
*)
  echo "this function is OSX specific"
;;
esac


