#!/usr/bin/zsh -f
RBENV_DIR=$HOME/.rbenv
RBINST_DIR=$RBENV_DIR/plugins/ruby-build

if [[ -d $RBENV_DIR ]]; then
  echo "$RBENV_DIR already exists, do you want to update it?"
  read answer
  if [[ $answer =~ ^ye?s?$ ]]; then
    cd $RBENV_DIR && git pull && cd -
    cd $RBINST_DIR && git pull && cd -
  fi
else
  git clone git://github.com/sstephenson/rbenv.git $RBENV_DIR &&
  git clone git://github.com/sstephenson/ruby-build.git $RBINST_DIR
fi
