#!/usr/bin/env zsh -f
# add default key to authorized_hosts on remote machine
	ID_FILE="${HOME}/.ssh/id_rsa.pub"

	if [ -z "`eval $GET_ID`" ] && [ -r "${ID_FILE}" ] ; then
	  GET_ID="cat ${ID_FILE}"
	fi

	if [ -z "`eval $GET_ID`" ]; then
	  notice "$0: ERROR: No identities found" >&2
	  return 1
	fi

	if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
	  notice "Usage: $0 [-i [identity_file]] [user@]machine" >&2
	  return 1
	fi

	{ eval "$GET_ID" ; } | ssh $1 "umask 077; test -d .ssh || mkdir .ssh ; cat >> .ssh/authorized_keys" || return 1

	echo "Done."
