# unicode
#export LANG=en_US.UTF-8

# for QT GTK+ theme
#export GTK2_RC_FILES=$HOME/.gtkrc-2.0

# fix java dialogs in tiling wms
#wmname LG3D &

# keymap settings
#setxkbmap -layout "lv,ru" \
#          -option "altwin:swap_alt_win" \
#          -option "caps:escape" \
#          -option "grp:alt_shift_toggle" \
#          -option "terminate:ctrl_alt_bksp" \

# disable bell
#xset b off

# keymap switcher
#xxkb &

# set wallpaper
#feh --bg-scale ~/.wallpaper &

# compositor
#compton &

# bind keys
#xbindkeys &

# remap keys
#( sleep 1 && xmodmap ~/.Xmodmap ) &

# hide mouse cursor when not used
#unclutter &

# term daemon
#urxvtd -q -f -o

# WM
#exec i3
