#!/usr/bin/env zsh
if [[ -z $1 || $1 == '-h' ]]; then
  echo "usage: $0 <jail name 1> [jail name x]"
  echo "\nconfigured jails:"
  grep " {" /etc/jail.conf | grep -v -e "^#" | cut -f 1 -d" "| sed 's/^/	/'
  return 1
fi
for j in $*; do
  echo "- stopping $j\n"
  /usr/local/bin/sudo /usr/sbin/jail -r $j
done;
