#!/usr/bin/env zsh
if [[ -z $1 || $1 == '-h' ]]; then
  echo "usage: $0 <portname>"
  return 1
fi

portdir=`whereis -sq $1`

if [[ ! -d $portdir ]]; then
  echo "no such port: $1"
  return 1
elif [[ $portdir =~ ^/usr/ports/.*$ ]]; then
  cd $portdir
fi 
