#!/usr/bin/env zsh -f
if [[ $1 =~ "[0-9]+" ]]; then
  sudo sysctl hw.snd.default_unit=$1
else 
  echo "$0 <pcm device number>"
  echo "\t set default output device"
  echo ""
  cat /dev/sndstat
  return 1
fi
